include:
  - project: invenia/gitlab-ci-helper
    file: /templates/ci-init.yml

stages:
  - build
  - deploy

.setup: &setup
  |
  echo "$ci_init" > ci_init && source ci_init && rm ci_init
  install_awscli
  package_install jq

"Build dashboard":
  stage: build
  before_script:
    - *setup
  script:
    - ./download_pipelines_info.sh
    - ./find_patterns_in_logs.py
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - "Build dashboard"
  script:
    # Used to validate the pipeline that generated the published documentation
    - echo "$CI_PIPELINE_ID" > public/pipeline_id.html
  artifacts:
    # As the dashboard is re-deployed daily the expiry just ensures that old artifacts
    # are eventually cleaned up
    expire_in: 1 week
    paths:
      - public/
  retry:
    max: 2
    when: runner_system_failure  # Work around issues with our docker-ci runners scaling down
