include:
  - project: invenia/gitlab-ci-helper
    file: /templates/ci-init.yml


.setup: &setup
  |
  echo "$ci_init" > ci_init && source ci_init && rm ci_init

pages:
  script:
  - ./download_pipelines_info.sh
  - ./find_patterns_in_logs.py
  artifacts:
    paths:
    - public
