include:
  - project: invenia/gitlab-ci-helper
    file: /templates/ci-init.yml

stages:
  - build
  - deploy

.setup: &setup
  |
  echo "$ci_init" > ci_init && source ci_init && rm ci_init
  install_awscli
  package_install git
  package_install jq
  package_install gzip

"Build dashboard":
  stage: build
  before_script:
    - *setup
  script:
    # Running our quick tests before building the dashboard.
    # TODO switch to pytest, setup tox, etc. and move tests to their own job
    # (https://gitlab.invenia.ca/invenia/wiki/blob/master/python/style-guide.md)
    - python3 -m unittest
    - ./download_pipelines_info.sh
    - ./find_patterns_in_logs.py
    # Compress files for faster transfer to the browser (especially large JSON files).
    # Alternatively on Mac: cd public && gzip -kfv *.json
    - find public -type f -regex '.*\.\(json\|htm\|html\|txt\|text\|js\|css\)$' -exec sh -c 'gzip < $0 > $0.gz' {} \;
    - ls -altrh public
  artifacts:
    paths:
    - public/
    # Link to the dashboard in the MR.
    # Unfortunately can't directly link to the index.html yet
    # https://gitlab.com/gitlab-org/gitlab/-/issues/220103
    expose_as: Dashboard
  retry:
    max: 2
    when: runner_system_failure

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - "Build dashboard"
  script:
    # Used to validate the pipeline that generated the published documentation
    - echo "$CI_PIPELINE_ID" > public/pipeline_id.html
  artifacts:
    # As the dashboard is re-deployed daily the expiry just ensures that old artifacts
    # are eventually cleaned up
    expire_in: 1 week
    paths:
      - public/
  retry:
    max: 2
    when: runner_system_failure  # Work around issues with our docker-ci runners scaling down
